# Generated by Django 3.0.3 on 2020-08-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wbl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='peer_review_mark',
            field=models.ManyToManyField(blank=True, related_name='peer_review_mark', through='wbl.PeerReviewMark', to='wbl.Criterion'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Criterion')),
                ('evaluation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Evaluation')),
                ('rater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_mark',
            },
        ),
        migrations.CreateModel(
            name='AcademicMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('criterion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Criterion')),
                ('evaluation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Evaluation')),
                ('rater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academic_mark',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='academic_mark',
            field=models.ManyToManyField(blank=True, related_name='academic_mark', through='wbl.AcademicMark', to='wbl.Criterion'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='mentor_mark',
            field=models.ManyToManyField(blank=True, related_name='mentor_mark', through='wbl.MentorMark', to='wbl.Criterion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Team'),
        ),
    ]
