# Generated by Django 3.0.3 on 2020-08-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0002_auto_20200826_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='member',
        ),
    ]
