# Generated by Django 3.0.3 on 2020-08-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0005_auto_20200828_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='academicReviewMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='mentorReviewMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='peerReviewMark',
            field=models.IntegerField(default=0),
        ),
    ]
