# Generated by Django 3.0.3 on 2020-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0007_auto_20200829_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='peer_review_mark',
            field=models.ManyToManyField(blank=True, related_name='peer_review_mark', through='wbl.PeerReviewMark', to='wbl.Criterion'),
        ),
    ]
