# Generated by Django 3.0.3 on 2020-08-28 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wbl', '0008_auto_20200829_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
