# Generated by Django 3.0.3 on 2020-08-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0009_task_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isFinish',
            field=models.BooleanField(default=False),
        ),
    ]
