# Generated by Django 3.0.3 on 2020-08-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0010_task_isfinish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
