# Generated by Django 3.0.3 on 2020-08-30 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wbl', '0013_auto_20200830_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, limit_choices_to=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
