# Generated by Django 3.0.3 on 2020-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0016_auto_20200830_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
