# Generated by Django 3.0.3 on 2020-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmark',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mentormark',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
