# Generated by Django 3.0.3 on 2020-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0019_auto_20200901_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='finalComment',
            new_name='academicComment',
        ),
        migrations.RemoveField(
            model_name='academicmark',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='mentormark',
            name='comment',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='mentorComment',
            field=models.TextField(default=' '),
        ),
    ]
