# Generated by Django 3.0.3 on 2020-09-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0021_auto_20200902_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='academicComment',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='mentorComment',
        ),
    ]
