# Generated by Django 3.0.3 on 2020-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0022_auto_20200902_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='academic_mark',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='isPass',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AcademicMark',
        ),
    ]
