# Generated by Django 3.0.3 on 2020-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0024_remove_evaluation_academicreviewmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isGraduate',
            field=models.BooleanField(default=False),
        ),
    ]
