# Generated by Django 3.0.3 on 2020-09-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0026_usercriterionmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wbl.Role'),
        ),
    ]
