# Generated by Django 3.0.3 on 2020-09-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbl', '0027_team_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
    ]
